/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cobra.accueil;


/**
 *
 * @author matt
 */
public class EmpreinteAccueilPanel extends javax.swing.JPanel {

  /**
   * Creates new form EmpreintePanel
   */
  public EmpreinteAccueilPanel() {
    initComponents();
    initState();
  }

  public void initState() {
    empreinteField.setText("");
    empreinteField.setSize(70, 78);
    matriculeField.setFocusable(true);
    matriculeField.requestFocus();
    matriculeField.setText("");
  }

  public String getEmpreinte(){
    return empreinteField.getText();
  }
  
    public String getMatricule(){
    return matriculeField.getText();
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empreinteLabel = new javax.swing.JLabel();
        empreinteField = new javax.swing.JTextField();
        matriculeLabel = new javax.swing.JLabel();
        matriculeField = new javax.swing.JTextField();

        empreinteLabel.setText("Posez votre doigt :");

        empreinteField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        empreinteField.setText("jTextField1");
        empreinteField.setMinimumSize(new java.awt.Dimension(20, 20));

        matriculeLabel.setText("Matricule Employé Temporaire :");

        matriculeField.setText("jTextField1");
        matriculeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculeFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(matriculeLabel)
                    .addComponent(empreinteLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empreinteField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matriculeField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matriculeLabel)
                    .addComponent(matriculeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empreinteField, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(empreinteLabel))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void matriculeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculeFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empreinteField;
    private javax.swing.JLabel empreinteLabel;
    private javax.swing.JTextField matriculeField;
    private javax.swing.JLabel matriculeLabel;
    // End of variables declaration//GEN-END:variables
}
