/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cobra.accueil;

import cobra.rh.*;


/**
 *
 * @author matt
 */
public class LoginPanelAccueil extends javax.swing.JPanel {

  /**
   * Creates new form LoginPanel
   */
  public LoginPanelAccueil() {
    initComponents();
    initState();
  }

  public void initState() {
    matriculeField.setText("");
    matriculeField.setFocusable(true);
    matriculeField.requestFocus();
    mdpField.setText("");
  }

  public String getMatricule(){
    return matriculeField.getText();
  }
  
  public String getMdp(){
    return mdpField.getText();
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    matriculeLabel = new javax.swing.JLabel();
    mdpLabel = new javax.swing.JLabel();
    matriculeField = new javax.swing.JTextField();
    mdpField = new javax.swing.JPasswordField();

    setPreferredSize(new java.awt.Dimension(350, 100));

    matriculeLabel.setText("Matricule :");

    mdpLabel.setText("Mot de passe :");

    matriculeField.setText("jTextField1");
    matriculeField.setNextFocusableComponent(mdpField);

    mdpField.setText("jPasswordField1");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(matriculeLabel)
          .addGroup(layout.createSequentialGroup()
            .addComponent(mdpLabel)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(matriculeField, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
              .addComponent(mdpField))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(matriculeLabel)
          .addComponent(matriculeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(mdpLabel)
          .addComponent(mdpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(38, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField matriculeField;
  private javax.swing.JLabel matriculeLabel;
  private javax.swing.JPasswordField mdpField;
  private javax.swing.JLabel mdpLabel;
  // End of variables declaration//GEN-END:variables
}
