/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cobra.accueil;

import cobra.PersonneTemporaire;

/**
 *
 * @author matt
 */
public class RecapPersonneTPanel extends javax.swing.JPanel {

  /**
   * Creates new form MdpPanel
   */
  public RecapPersonneTPanel() {
    initComponents();
    initState();
  }

  public void initState() {
    nomLabel.setText("");
    prenomLabel.setText("");
    matLabel.setText("");
    photoLabel.setText("");
  }
  
  public void setRecap(PersonneTemporaire p){
    nomLabel.setText(p.getNom());
    prenomLabel.setText(p.getPrenom());
    matLabel.setText(p.getMatricule().getMat());
    photoLabel.setText(p.getPhoto());
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomEmpLabel = new javax.swing.JLabel();
        prenomEmpLabel = new javax.swing.JLabel();
        photoEmpLabel = new javax.swing.JLabel();
        matEmpLabel = new javax.swing.JLabel();
        matLabel = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();

        nomEmpLabel.setText("Nom de l'employé");

        prenomEmpLabel.setText("Prénom de l'employé :");

        photoEmpLabel.setText("Photo de l'employé : ");

        matEmpLabel.setText("Matricule de l'employé");

        matLabel.setText("jLabel1");

        nomLabel.setText("jLabel2");

        prenomLabel.setText("jLabel2");

        photoLabel.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prenomEmpLabel)
                    .addComponent(nomEmpLabel)
                    .addComponent(matEmpLabel)
                    .addComponent(photoEmpLabel))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photoLabel)
                    .addComponent(prenomLabel)
                    .addComponent(nomLabel)
                    .addComponent(matLabel))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matEmpLabel)
                    .addComponent(matLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomEmpLabel)
                    .addComponent(nomLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomEmpLabel)
                    .addComponent(prenomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoEmpLabel)
                    .addComponent(photoLabel))
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel matEmpLabel;
    private javax.swing.JLabel matLabel;
    private javax.swing.JLabel nomEmpLabel;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JLabel photoEmpLabel;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel prenomEmpLabel;
    private javax.swing.JLabel prenomLabel;
    // End of variables declaration//GEN-END:variables
}
