/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cobra.responsable;

import cobra.Personne;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JTextField;
import javax.swing.ListModel;

/**
 *
 * @author matt
 */
public class RecherchePanel extends javax.swing.JPanel {
  
  private ListModel<PersonneListModel> personnes;

  /**
   * Creates new form RecherchePanel
   */
  public RecherchePanel() {
	initComponents();
	initState();
  }

  public void initState() {
	matriculeField.setEnabled(true);
	nomField.setEnabled(true);
	prenomField.setEnabled(true);
	
	matriculeField.setText("");
	matriculeField.setFocusable(true);
	matriculeField.requestFocus();
	nomField.setText("");
	nomField.setFocusable(true);
	prenomField.setText("");
	prenomField.setFocusable(true);
	
	personnes = new DefaultListModel<>();
	personneList.setModel(personnes);
  }

  public void initTrouve(ArrayList<Personne> p){
	matriculeField.setEnabled(false);
	nomField.setEnabled(false);
	prenomField.setEnabled(false);
	
	personneList.clearSelection();
	personnes = Personne.getListModel(p);
	personneList.setModel(personnes);
  }
  
  public String getMatricule() {
	return matriculeField.getText();
  }

  public String getNom() {
	return nomField.getText();
  }

  public String getPrenom() {
	return prenomField.getText();
  }
  
  public Personne getSelectedPersonne() throws AucuneSelectionException{
	PersonneListModel pSelect = (PersonneListModel) personneList.getSelectedValue();
	if(pSelect == null)
	  throw new AucuneSelectionException("Aucune personne selectionnée.");
	return pSelect.getPersonne();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    matriculeField = new javax.swing.JTextField();
    nomField = new javax.swing.JTextField();
    prenomField = new javax.swing.JTextField();
    jScrollPane2 = new javax.swing.JScrollPane();
    personneList = new javax.swing.JList();

    jList1.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(jList1);

    setPreferredSize(new java.awt.Dimension(258, 171));

    jLabel1.setText("Matricule :");

    jLabel2.setText("Nom :");

    jLabel3.setText("Prénom :");

    matriculeField.setText("jTextField1");

    nomField.setText("jTextField2");

    prenomField.setText("jTextField3");

    personneList.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    jScrollPane2.setViewportView(personneList);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
              .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(nomField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
              .addComponent(matriculeField, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(prenomField))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(matriculeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(nomField)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(prenomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JList jList1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextField matriculeField;
  private javax.swing.JTextField nomField;
  private javax.swing.JList personneList;
  private javax.swing.JTextField prenomField;
  // End of variables declaration//GEN-END:variables
}
