/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testidl.borne;

/**
 *
 * @author matt
 */
public class BorneFrame extends javax.swing.JFrame {

  private Borne borne;
  
  private enum ETAT { NONCONNECTE, CHANGEMDP, EMPREINTE, EMPREINTECHANGEE };
  
  private ETAT etat;
  
  /**
   * Creates new form BorneFrame
   */
  public BorneFrame() {
	initComponents();
	
	initState();
	
	this.setSize(400, 200);
	
  }

  private void initState(){
	etat = ETAT.NONCONNECTE;
	loginPanel.setVisible(true);
	mdpPanel.setVisible(false);
	empreintePanel.setVisible(false);
	finPanel.setVisible(false);
	
	loginPanel.initState();
	mdpPanel.initState();
	empreintePanel.initState();
	finPanel.initState();
  }
  
  public void versEmpreinte(){
	etat = ETAT.EMPREINTE;
	loginPanel.setVisible(false);
	mdpPanel.setVisible(false);
	empreintePanel.setVisible(true);
	finPanel.setVisible(false);
  }
  
  public void versMdp(){
	etat = ETAT.CHANGEMDP;
	loginPanel.setVisible(false);
	mdpPanel.setVisible(true);
	empreintePanel.setVisible(false);
	finPanel.setVisible(false);
  }
  
  public void versEmpreinteChangee(){
	etat = ETAT.EMPREINTECHANGEE;
	loginPanel.setVisible(false);
	mdpPanel.setVisible(false);
	empreintePanel.setVisible(false);
	finPanel.setVisible(true);
	finPanel.startTimer();
  }
  
  public void versConnexion(){
	initState();
  }
  
  public void setBorne(Borne borne){
	this.borne = borne;
	loginPanel.setBorne(borne);
	mdpPanel.setBorne(borne);
	empreintePanel.setBorne(borne);
	finPanel.setBorne(borne);
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    loginPanel = new testidl.borne.LoginPanel();
    mdpPanel = new testidl.borne.MdpPanel();
    finPanel = new testidl.borne.FinPanel();
    empreintePanel = new testidl.borne.EmpreintePanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(finPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(mdpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(empreintePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(finPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(empreintePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(mdpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		  javax.swing.UIManager.setLookAndFeel(info.getClassName());
		  break;
		}
	  }
	} catch (ClassNotFoundException ex) {
	  java.util.logging.Logger.getLogger(BorneFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	  java.util.logging.Logger.getLogger(BorneFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	  java.util.logging.Logger.getLogger(BorneFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	  java.util.logging.Logger.getLogger(BorneFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
        //</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	  public void run() {
		new BorneFrame().setVisible(true);
	  }
	});
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private testidl.borne.EmpreintePanel empreintePanel;
  private testidl.borne.FinPanel finPanel;
  private testidl.borne.LoginPanel loginPanel;
  private testidl.borne.MdpPanel mdpPanel;
  // End of variables declaration//GEN-END:variables
}
