/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testidl.borne;

import testidl.Empreinte;

/**
 *
 * @author matt
 */
public class EmpreintePanel extends javax.swing.JPanel {

  private Borne borne;

  /**
   * Creates new form EmpreintePanel
   */
  public EmpreintePanel() {
    initComponents();

    initState();
  }

  public void initState() {
    empreinteField.setText("");
    empreinteField.setSize(70, 78);
    empreinteField.setFocusable(true);
    empreinteField.requestFocus();
  }

  public String getEmpreinte(){
    return empreinteField.getText();
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    empreinteLabel = new javax.swing.JLabel();
    empreinteField = new javax.swing.JTextField();

    empreinteLabel.setText("Posez votre doigt :");

    empreinteField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    empreinteField.setText("jTextField1");
    empreinteField.setMinimumSize(new java.awt.Dimension(20, 20));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(62, Short.MAX_VALUE)
        .addComponent(empreinteLabel)
        .addGap(18, 18, 18)
        .addComponent(empreinteField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(109, 109, 109))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(empreinteField, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
          .addComponent(empreinteLabel))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField empreinteField;
  private javax.swing.JLabel empreinteLabel;
  // End of variables declaration//GEN-END:variables
}
