/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testidl.borne;

import controleAcces.annuairePackage.loginIncorrectException;
import controleAcces.annuairePackage.personneInexistanteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author matt
 */
public class LoginPanel extends javax.swing.JPanel {

  private Borne borne;

  /**
   * Creates new form LoginPanel
   */
  public LoginPanel() {
	initComponents();

	initState();
	errorLabel.setText("");
  }

  public void initState() {
	titreLabel.setText("LOGIN");
	matriculeField.setText("");
	matriculeField.setFocusable(true);
	matriculeField.requestFocus();
	mdpField.setText("");
  }

  public void setBorne(Borne borne) {
	this.borne = borne;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    matriculeLabel = new javax.swing.JLabel();
    mdpLabel = new javax.swing.JLabel();
    matriculeField = new javax.swing.JTextField();
    mdpField = new javax.swing.JTextField();
    connectButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    errorLabel = new javax.swing.JLabel();
    titreLabel = new javax.swing.JLabel();

    matriculeLabel.setText("Matricule :");

    mdpLabel.setText("Mot de passe :");

    matriculeField.setText("jTextField1");
    matriculeField.setNextFocusableComponent(mdpField);

    mdpField.setText("jTextField2");
    mdpField.setNextFocusableComponent(connectButton);

    connectButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    connectButton.setText("Connect");
    connectButton.setNextFocusableComponent(cancelButton);
    connectButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        connectButtonActionPerformed(evt);
      }
    });

    cancelButton.setText("Cancel");
    cancelButton.setNextFocusableComponent(matriculeField);
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    errorLabel.setForeground(new java.awt.Color(255, 0, 0));
    errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    errorLabel.setText("jLabel1");
    errorLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    titreLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    titreLabel.setText("LOGIN");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectButton))
              .addComponent(matriculeLabel))
            .addGap(0, 101, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(mdpLabel)
              .addComponent(titreLabel))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(errorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(matriculeField)
              .addComponent(mdpField))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(titreLabel))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(matriculeLabel)
          .addComponent(matriculeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(mdpLabel)
          .addComponent(mdpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(connectButton)
          .addComponent(cancelButton))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
	String mat = matriculeField.getText();
	String mdp = mdpField.getText();

	try {
	  borne.authentifier(mat, mdp);
	} catch (loginIncorrectException ex) {
	  errorLabel.setText(ex.message);
	  initState();
	} catch (personneInexistanteException ex) {
	  Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
	}
  }//GEN-LAST:event_connectButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    borne.quitter();
  }//GEN-LAST:event_cancelButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JButton connectButton;
  private javax.swing.JLabel errorLabel;
  private javax.swing.JTextField matriculeField;
  private javax.swing.JLabel matriculeLabel;
  private javax.swing.JTextField mdpField;
  private javax.swing.JLabel mdpLabel;
  private javax.swing.JLabel titreLabel;
  // End of variables declaration//GEN-END:variables
}
