/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testidl.borne;

import controleAcces.annuairePackage.mdpIdentiqueException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author matt
 */
public class MdpPanel extends javax.swing.JPanel {

  /**
   * Creates new form MdpPanel
   */
  public MdpPanel() {
    initComponents();
    initState();
  }

  public void initState() {
    mdp1Field.setText("");
    mdp1Field.setFocusable(true);
    mdp1Field.requestFocus();
    mdp2Field.setText("");
  }
  
  public String getMdp1(){
    return mdp1Field.getText();
  }
  
  public String getMdp2(){
    return mdp2Field.getText();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    mdp1Field = new javax.swing.JTextField();
    mdp2Field = new javax.swing.JTextField();
    mdp1Label = new javax.swing.JLabel();
    mdp2Label = new javax.swing.JLabel();

    mdp1Field.setText("jTextField1");

    mdp2Field.setText("jTextField2");

    mdp1Label.setText("Tapez votre mot de passe :");

    mdp2Label.setText("Retapez votre mot de passe :");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(mdp1Label)
            .addGap(18, 18, 18))
          .addGroup(layout.createSequentialGroup()
            .addComponent(mdp2Label)
            .addGap(7, 7, 7)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(mdp2Field, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
          .addComponent(mdp1Field))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(mdp1Label)
          .addComponent(mdp1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(mdp2Label)
          .addComponent(mdp2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(37, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField mdp1Field;
  private javax.swing.JLabel mdp1Label;
  private javax.swing.JTextField mdp2Field;
  private javax.swing.JLabel mdp2Label;
  // End of variables declaration//GEN-END:variables
}
