/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cobra.responsableZone;

import java.util.ArrayList;

/**
 *
 * @author Mélanie
 */
public class AutoriserPanel extends javax.swing.JPanel {

    /**
     * Creates new form AutoriserPanel
     */
    public AutoriserPanel() {
        initComponents();
    }
    
     public String getHeureD(){
        return heureDField.getText();
    }
     public String getMinuteD(){
        return minuteDField.getText();
    }
      public String getHeureF(){
        return heureFField.getText();
    }
     public String getMinuteF(){
        return minuteFField.getText();
    }
     public String getJourD(){
        return jourDField.getText();
    }
     public String getJourF(){
        return jourFField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personnesComboBox = new javax.swing.JComboBox<>();
        heureDLabel = new javax.swing.JLabel();
        minuteDLabel = new javax.swing.JLabel();
        heureFLabel = new javax.swing.JLabel();
        minuteFLabel = new javax.swing.JLabel();
        jourDLabel = new javax.swing.JLabel();
        jourFLabel = new javax.swing.JLabel();
        heureDField = new javax.swing.JTextField();
        heureFField = new javax.swing.JTextField();
        minuteDField = new javax.swing.JTextField();
        minuteFField = new javax.swing.JTextField();
        jourDField = new javax.swing.JTextField();
        jourFField = new javax.swing.JTextField();

        personnesComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                personnesComboBoxItemStateChanged(evt);
            }
        });

        heureDLabel.setText("Heure Début");

        minuteDLabel.setText("Minute Début");

        heureFLabel.setText("Heure Fin");

        minuteFLabel.setText("Minute Fin");

        jourDLabel.setText("Jour Début");

        jourFLabel.setText("Jour Fin");

        heureDField.setText("jTextField1");

        heureFField.setText("jTextField1");

        minuteDField.setText("jTextField1");

        minuteFField.setText("jTextField1");

        jourDField.setText("jTextField1");

        jourFField.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jourFLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jourDLabel)
                            .addGap(318, 318, 318)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jourFField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(107, 107, 107)
                                    .addComponent(jourDField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(heureDLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(heureDField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(heureFLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(heureFField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(minuteDLabel)
                                    .addComponent(minuteFLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(minuteFField, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                    .addComponent(minuteDField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(personnesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(personnesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heureDLabel)
                    .addComponent(minuteDLabel)
                    .addComponent(heureDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuteDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minuteFLabel)
                    .addComponent(heureFField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuteFField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heureFLabel))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jourDLabel)
                    .addComponent(jourDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jourFLabel)
                    .addComponent(jourFField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void personnesComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_personnesComboBoxItemStateChanged
        if( null != getSelectedPersonne()){
            if (getSelectedPersonne().startsWith("t")){
                jourDField.setEnabled(true);
                jourFField.setEnabled(true);            
            }
            else {
                jourDField.setEnabled(false);
                jourFField.setEnabled(false);
            }
        }
    }//GEN-LAST:event_personnesComboBoxItemStateChanged


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField heureDField;
    private javax.swing.JLabel heureDLabel;
    private javax.swing.JTextField heureFField;
    private javax.swing.JLabel heureFLabel;
    private javax.swing.JTextField jourDField;
    private javax.swing.JLabel jourDLabel;
    private javax.swing.JTextField jourFField;
    private javax.swing.JLabel jourFLabel;
    private javax.swing.JTextField minuteDField;
    private javax.swing.JLabel minuteDLabel;
    private javax.swing.JTextField minuteFField;
    private javax.swing.JLabel minuteFLabel;
    private javax.swing.JComboBox<String> personnesComboBox;
    // End of variables declaration//GEN-END:variables

    public void initState(ArrayList<String> listePersonnes) {
        heureDField.setText("");
        heureDField.setFocusable(true);
        heureDField.requestFocus();
        minuteDField.setText("");
        minuteFField.setText("");
        heureFField.setText("");
        jourDField.setText("");
        jourFField.setText("");
        
        personnesComboBox.removeAllItems();
        for (String p : listePersonnes){
            personnesComboBox.addItem(p);
        }
        if (null != personnesComboBox.getSelectedItem()){
            if (getSelectedPersonne().startsWith("t")){
                jourDField.setEnabled(true);
                jourFField.setEnabled(true);            
            }
            else {
                jourDField.setEnabled(false);
                jourFField.setEnabled(false);
            }
        }
    }
    
    public String getSelectedPersonne(){
         return(String)personnesComboBox.getSelectedItem();
    }
}
